[package]
name = "roguelike"
version = "0.1.0"
edition = "2018"
license = "AGPL-3.0-only"

[dependencies]
legion = "0.2"
rand = "0.7"
rand_distr = "0.2"
rand_pcg = "0.2"
sdl2 = { version = "0.32", features = ["image", "ttf", "gfx"] }
noise = { version = "0.6", default-features = false }
